### ISSUE TITLE
Can't parse in arguments with a space in it

### ISSUE THREAD

**Issue by AceKiron** [pfultz2/args#2]
When I try `helloworld.exe -N "Nobody, or am I?" -C 4` it should see the following arguments because of how command line works:

- -N
- "Nobody, or am I?"
- -C
- 4

but it actually only sees this:

- -N
- Nobody,
- -C
- 4

Can you fix this please? I'm using an almost entirely exact copy of the example except for the -h argument which doesn't work.

**Comment by pfultz2** [comment]
Fixed that here:

https://github.com/pfultz2/args/commit/2afcc7f841b6949947522eaf5f43cc36cb6d82bf

When it passes travis, I'll merge it into master.
